# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='country_prefix_en_us',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='country_prefix_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='country_prefix_uk',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
