# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170320_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='country_prefix_en_us',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='country_prefix_ru',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='country_prefix_uk',
        ),
    ]
