# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 04:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_title', models.CharField(max_length=200, verbose_name='Title')),
                ('discount_code', models.CharField(max_length=20, verbose_name='Code')),
                ('discount_range', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Range')),
                ('discount_type', models.CharField(choices=[('F_A', 'Coupon')], default='F_A', max_length=20, verbose_name='Title')),
                ('discount_start_period', models.DateTimeField(verbose_name='Start period')),
                ('discount_end_period', models.DateTimeField(verbose_name='End period')),
                ('discount_description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Discounts',
                'verbose_name': 'Discount',
            },
        ),
    ]
