# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=240, unique=True, verbose_name='Email')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-date_added'],
                'verbose_name': 'Subscriber',
            },
        ),
    ]
