# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=240, unique=True, verbose_name='Email'),
        ),
    ]
