# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_first_name', models.CharField(max_length=100)),
                ('shipping_last_name', models.CharField(max_length=100)),
                ('shipping_type', models.CharField(choices=[('USA_S', 'USA Shipping'), ('I_S', 'International Shipping (We will call you back to clarify the details)')], default='I_S', max_length=50)),
                ('shipping_street', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_home', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_postcode', models.CharField(blank=True, max_length=15, null=True)),
                ('shipping_country', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_to_home', models.BooleanField(default=False)),
                ('shipping_phone', models.CharField(max_length=20)),
                ('shipping_email', models.EmailField(max_length=254)),
                ('pay_type', models.CharField(choices=[('N', 'Now'), ('W_R', 'When receiving')], default='N', max_length=40)),
                ('pay_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'ordering': ['-created'],
                'verbose_name': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariation')),
            ],
            options={
                'verbose_name_plural': 'Order items',
                'verbose_name': 'Order item',
            },
        ),
    ]
