# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_auto_20170403_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_first_name', models.CharField(max_length=100)),
                ('shipping_last_name', models.CharField(max_length=100)),
                ('shipping_type', models.CharField(choices=[('N_P', 'New Post'), ('A_V', 'Another variant')], default='A_V', max_length=50)),
                ('shipping_street', models.CharField(max_length=200, null=True)),
                ('shipping_state', models.CharField(max_length=100, null=True)),
                ('shipping_postcode', models.CharField(max_length=15, null=True)),
                ('shipping_country', models.CharField(max_length=50, null=True)),
                ('shipping_city', models.CharField(max_length=100, null=True)),
                ('shipping_departament', models.CharField(max_length=400, null=True)),
                ('shipping_to_home', models.BooleanField(default=False)),
                ('shipping_phone', models.CharField(max_length=20)),
                ('shipping_email', models.EmailField(max_length=254)),
                ('shipping_total', models.FloatField()),
                ('discount_code', models.CharField(max_length=20, null=True)),
                ('total', models.FloatField()),
                ('item_total', models.IntegerField()),
                ('pay_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariation')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
            },
        ),
    ]
