# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.CharField(choices=[('N', 'Now'), ('W_R', 'When receiving (for New Post only)')], default='N', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('N_P', 'New Post'), ('A_V', 'Another variant (We will call you back to clarify the details)')], default='A_V', max_length=50),
        ),
    ]
