# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170404_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_home',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
