# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170406_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Discount'),
        ),
    ]
