# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170406_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.Discount'),
        ),
    ]
