# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20170710_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_code',
        ),
    ]
