# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('title_en_us', models.CharField(max_length=500, null=True, unique=True)),
                ('title_ru', models.CharField(max_length=500, null=True, unique=True)),
                ('title_uk', models.CharField(max_length=500, null=True, unique=True)),
                ('is_published', models.CharField(choices=[(True, 'Published'), (False, 'Draft')], default=False, max_length=20)),
                ('pretext', models.TextField()),
                ('pretext_en_us', models.TextField(null=True)),
                ('pretext_ru', models.TextField(null=True)),
                ('pretext_uk', models.TextField(null=True)),
                ('content', models.TextField()),
                ('content_en_us', models.TextField(null=True)),
                ('content_ru', models.TextField(null=True)),
                ('content_uk', models.TextField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('title_en_us', models.CharField(max_length=30, null=True, unique=True)),
                ('title_ru', models.CharField(max_length=30, null=True, unique=True)),
                ('title_uk', models.CharField(max_length=30, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('description_en_us', models.CharField(blank=True, max_length=1000, null=True)),
                ('description_ru', models.CharField(blank=True, max_length=1000, null=True)),
                ('description_uk', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='bloggiz.Tag'),
        ),
    ]
