# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloggiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en_us',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_uk',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.CharField(choices=[(True, 'Published'), (False, 'Draft')], default=False, max_length=20, verbose_name='Is published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pretext',
            field=models.TextField(verbose_name='Short content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pretext_en_us',
            field=models.TextField(null=True, verbose_name='Short content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pretext_ru',
            field=models.TextField(null=True, verbose_name='Short content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pretext_uk',
            field=models.TextField(null=True, verbose_name='Short content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='bloggiz.Tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=500, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_uk',
            field=models.CharField(max_length=500, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_en_us',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_uk',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title_en_us',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title_uk',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Title'),
        ),
    ]
