# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggiz', '0002_auto_20170408_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
