# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 23:18
from __future__ import unicode_literals

import bloggiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggiz', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_picture',
            field=models.FileField(null=True, upload_to=bloggiz.models.upload_path),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
