# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggiz', '0005_auto_20170409_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(choices=[(True, 'Published'), (False, 'Draft')], default=False, verbose_name='Is published'),
        ),
    ]
