# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloggiz', '0006_auto_20170409_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Author')),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(verbose_name='Comment')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloggiz.Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['date_added'],
            },
        ),
    ]
