# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 15:07
from __future__ import unicode_literals

import bloggiz.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bloggiz', '0011_auto_20170514_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_picture',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=bloggiz.models.upload_path, verbose_name='Cover picture'),
        ),
    ]
