# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 11:45
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bloggiz', '0013_auto_20170716_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('cover_picture', '300x430', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
