# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 12:33
from __future__ import unicode_literals

import bloggiz.models
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bloggiz', '0015_auto_20170717_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('cover_picture', '300x430', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_picture',
            field=models.ImageField(blank=True, upload_to=bloggiz.models.upload_path),
        ),
    ]
