# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_title', models.CharField(max_length=200)),
                ('discount_range', models.IntegerField()),
                ('discount_code', models.CharField(max_length=20)),
                ('discount_type', models.CharField(max_length=100)),
                ('discount_start_period', models.DateTimeField()),
                ('discount_end_period', models.DateTimeField()),
                ('discount_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_first_name', models.CharField(max_length=100)),
                ('billing_last_name', models.CharField(max_length=100)),
                ('shipping_first_name', models.CharField(max_length=100)),
                ('shipping_last_name', models.CharField(max_length=100)),
                ('shipping_type', models.CharField(max_length=50)),
                ('shipping_street', models.CharField(max_length=200, null=True)),
                ('shipping_state', models.CharField(max_length=100, null=True)),
                ('shipping_postcode', models.CharField(max_length=15, null=True)),
                ('shipping_country', models.CharField(max_length=50, null=True)),
                ('shipping_city', models.CharField(max_length=100, null=True)),
                ('shipping_departament', models.CharField(max_length=400, null=True)),
                ('shipping_to_home', models.BooleanField()),
                ('shipping_phone', models.CharField(max_length=20)),
                ('shipping_email', models.EmailField(max_length=254)),
                ('shipping_total', models.FloatField()),
                ('discount_code', models.CharField(max_length=20, null=True)),
                ('total', models.FloatField()),
                ('item_total', models.IntegerField()),
                ('pay_status', models.BooleanField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Order')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField()),
                ('status', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=products.models.upload_path)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_main', models.BooleanField()),
                ('main_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Products images',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Products Reviews',
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=20, unique=True)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('is_new', models.BooleanField()),
                ('is_available', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name': 'Product variation',
                'verbose_name_plural': 'Products variations',
            },
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariation'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariation'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariation'),
        ),
    ]
