# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:12
from __future__ import unicode_literals

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('status', models.BooleanField(choices=[(True, 'Published'), (False, 'Draft')], default=False, verbose_name='Status')),
                ('is_new', models.BooleanField(default=False, verbose_name='Is new')),
                ('is_available', models.BooleanField(default=False, verbose_name='Is available')),
                ('image', models.FileField(upload_to=products.models.upload_path, verbose_name='Image')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('htu', models.TextField(blank=True, verbose_name='Benefits and how to use info')),
                ('composition', models.TextField(blank=True, verbose_name='Composition')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'verbose_name': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=products.models.upload_path)),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Products images',
                'ordering': ['-is_main'],
                'verbose_name': 'Product image',
            },
        ),
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('name', models.CharField(max_length=240)),
                ('email', models.CharField(max_length=240)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductQuestion', verbose_name='Parent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Product Questions',
                'ordering': ['-date_added'],
                'verbose_name': 'Product Question',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('review_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name_plural': 'Products Reviews',
                'verbose_name': 'Product Review',
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, null=True, unique=True, verbose_name='Sku')),
                ('color_description', models.CharField(blank=True, max_length=50, verbose_name='Color description')),
                ('color_value', colorfield.fields.ColorField(default='#FF0000', max_length=10, verbose_name='Color value')),
                ('status', models.BooleanField(choices=[(True, 'Published'), (False, 'Draft')], default=False, verbose_name='Status')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Products variations',
                'verbose_name': 'Product variation',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(null=True)),
                ('status', models.BooleanField(choices=[(True, 'Published'), (False, 'Draft')], default=False, verbose_name='Status')),
                ('category', models.ManyToManyField(to='products.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'verbose_name': 'Sub Category',
            },
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductVariation'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.SubCategory', verbose_name='Sub categories'),
        ),
    ]
