# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productreview_review_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='title',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
