# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 23:41
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
