# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 23:30
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170308_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main'], 'verbose_name': 'Product image', 'verbose_name_plural': 'Products images'},
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='color',
            new_name='color_description',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='color_value',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=10),
        ),
    ]
