# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 22:55
from __future__ import unicode_literals

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170317_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=20, null=True, unique=True)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('color_description', models.CharField(blank=True, max_length=50)),
                ('color_value', colorfield.fields.ColorField(default='#FF0000', max_length=10)),
                ('is_new', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('status', models.BooleanField(choices=[(True, 'Published'), (False, 'Draft')], default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Product variation',
                'verbose_name_plural': 'Products variations',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariation'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[(True, 'Published'), (False, 'Draft')], default=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductVariation'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariation'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
