# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 04:03
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170318_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en_us',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uk',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en_us',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='description_en_us',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='description_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='description_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='color_description_en_us',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='color_description_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='color_description_uk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='description_en_us',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='description_uk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='title_en_us',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='title_uk',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
