# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170319_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_description_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_title_en_us',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_title_uk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
