# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_auto_20170511_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('name', models.CharField(max_length=240)),
                ('email', models.CharField(max_length=240)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductQuestion', verbose_name='Parent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-date_added'],
                'verbose_name': 'Product Question',
                'verbose_name_plural': 'Product Questions',
            },
        ),
        migrations.RemoveField(
            model_name='productanswer',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='productanswer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productanswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductAnswer',
        ),
    ]
