# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 18:40
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20170511_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('status', models.BooleanField(choices=[(True, 'Published'), (False, 'Draft')], default=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[(True, 'Published'), (False, 'Draft')], default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en_us',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='color_description',
            field=models.CharField(blank=True, max_length=50, verbose_name='Color description'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='color_description_en_us',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color description'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='color_description_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color description'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='color_description_uk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color description'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='color_value',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=10, verbose_name='Color value'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Is available'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is new'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='status',
            field=models.BooleanField(choices=[(True, 'Published'), (False, 'Draft')], default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='title_en_us',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='title_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='sub_categories',
            field=models.ManyToManyField(to='products.SubCategory', verbose_name='Sub categories'),
        ),
    ]
