# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20170512_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='title_en_us',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
    ]
