# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20170514_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='sub_categories',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Is available'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is new'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_categories',
            field=models.ManyToManyField(to='products.SubCategory', verbose_name='Sub categories'),
        ),
    ]
