# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20170515_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='datetime', upload_to=products.models.upload_path),
            preserve_default=False,
        ),
    ]
