# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
    ]
