# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20170522_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to=products.models.upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Sku'),
        ),
    ]
