# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 00:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20170626_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount_product',
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_range',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('F_A', 'Coupon')], default='F_A', max_length=20),
        ),
    ]
