# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 10:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20170706_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_end_period',
            field=models.DateTimeField(verbose_name='End period'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_range',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Range'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_start_period',
            field=models.DateTimeField(verbose_name='Start period'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('F_A', 'Coupon')], default='F_A', max_length=20, verbose_name='Title'),
        ),
    ]
