# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20170710_0404'),
        ('products', '0028_auto_20170706_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
