# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_delete_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, verbose_name='Composition'),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='product',
            name='htu',
            field=models.TextField(blank=True, verbose_name='How to use'),
        ),
    ]
