# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20170714_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=240, unique=True, verbose_name='Word')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active?')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.ManyToManyField(to='products.Keyword', verbose_name='Keywords'),
        ),
    ]
