# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20170715_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.ManyToManyField(null=True, to='products.Keyword', verbose_name='Keywords'),
        ),
    ]
