# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20170715_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
    ]
