# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20170802_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='htu',
            field=models.TextField(blank=True, verbose_name='Benefits and how to use info'),
        ),
    ]
