# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20170819_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
